### PR TITLE
GitHub Repo House Keeping

### PR DESCRIPTION
**Pull request by mitch7391**
Hey @codyc1515, I have taken some time to try and add a bit more user-friendliness to your GitHub page. Changes in this PR:

- I have created a README page similar to what you would see on most plug-ins.
   - A nice logo has been added.
   - NPM badges have been added.
   - Installation instructions have been added.
   - A config sample has been added.
   - A 'credit' area has been added for people who have contributed to the plug-in.
- I have created a Licence (MIT) for the plug-in.
- I have created a CHANGELOG that will appear in Homebridge UI. It has not been populated with you previous versions (you will have to do that).
- I have created ISSUE templates for the following:
   - Bug Report.
   - Feature Request.
   - Support Request.

Nothing in this PR should be breaking. All you would have to do is merge the PR and update your version number in your `package.json`, potentially add anything else in the CHANGELOG and create a new GitHub release (I notice this is currently behind your latest). Please let me know if you have any questions or issues.

### CODE REVIEW

**Comment by mitch7391** [comment]
Thanks for merging this @codyc1515. Before you do any sort of publish to npm, you will need to edit the date in the changelog and maybe create a new GitHub release; seen as it looks like it has confused a user already that they do not match.

**Comment by codyc1515** [comment]
Hey there. First of all thank you for taking the time to contribute to this project. It is very much appreciated! Since a new arrival I have very limited time to spend on these kinds of things and sometimes when I do a fix I miss things off, like you say around the releases and versions. So I will endeavour to get these sorted at some point. Thank you again.

**Comment by mitch7391** [comment]
All good @codyc1515, I try to help out where I can with plug-ins I use and have only recently learned enough to get my own repo into Homebridge UI; although it it not it’s own stand alone plug-in. So, some of the stuff I have recently learned I have tried to see if I can help people out :) I think I want to tackle your `package.json` next as it seems very different to most I have seen. I’ll probably create another fork, have a play and make sure I do not break anything and if it’s looking all good I’ll submit a PR for your review. That would be testing new waters for me to learn with!

**Comment by codyc1515** [comment]
Good to hear. I think we can easily fix the package.json just using npm. I can hopefully take a look at this in the next few days or so.

**Comment by mitch7391** [comment]
Ok, I will leave that with you then; let me know if you cannot get around to it and I’ll take a look. I trust you would do a better job haha…

**Pull request merged**
